// swift-tools-version: 6.0
import PackageDescription

// Production MLS engine core. MLSBridge and the XCFramework are generated by
// build-bridge.sh from the M1.5-qualified pin and patches; never committed.
let package = Package(
    name: "WatchlinkMLS",
    platforms: [.iOS(.v17), .macOS(.v14)],
    products: [
        .library(name: "WatchlinkMLS", targets: ["WatchlinkMLS"]),
        .library(name: "MLSBridge", targets: ["MLSBridge"]),
        .library(name: "ProtectedStateStore", targets: ["ProtectedStateStore"]),
    ],
    targets: [
        .binaryTarget(name: "mls_rs_uniffiFFI", path: "Artifacts/MLSBridgeFFI.xcframework"),
        .target(name: "MLSBridge", dependencies: ["mls_rs_uniffiFFI"]),
        .target(name: "ProtectedStateStore"),
        .target(name: "WatchlinkMLS", dependencies: ["MLSBridge", "ProtectedStateStore"]),
    ]
)
